networks:
  server:
    driver: bridge

services:
  node:
    container_name: server_node
    build:
      context: ./api
      dockerfile: ../docker/node/Dockerfile
    restart: unless-stopped
    working_dir: /usr/src/app
    networks:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/usr/src/app/src
    command: npm start

  redis:
    container_name: server_redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    networks:
      - server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/usr/local/etc/redis/data

volumes:
  redis-data:
